
namespace Windows.Foundation.Metadata {

  [attributeusage(target_runtimeclass, target_interface, target_struct, target_enum, target_delegate, target_field, target_property, target_method, target_event)]
  [attributename("doc_string")]
  attribute DocStringAttribute {
    String Content;
  }

  [attributeusage(target_property, target_method)]
  [attributename("doc_default")] attribute DocDefaultAttribute {
    String Content;
  } 
}
